server:
  port: 8003
spring:
  application:
    name: provider-ticket
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/
  instance:
    hostname: provider-ticket #实例的主机名
    prefer-ip-address: true #注册服务的时候使用服务的IP地址
