server:
  port: 8200
spring:
  application:
    name: gateway


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/
    fetch-registry: true
    register-with-eureka: true
zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  routes:
  - id: provider
    #路由到微服务配置-微服务的path路径有项目名需自带，服务发现只有IP与端口信息
    uri: lb://provider-ticket
    predicates:
    #匹配路径表达式
    - Path=/provider-ticket/**
    filters:
    - StripPrefix=1

hystrix:
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 2000000

ribbon:
   eureka:
      enabled: true
   ReadTimeout: 600000
